ARG CUDA=12.4.1
FROM nvidia/cuda:${CUDA}-cudnn-runtime-ubuntu22.04
# FROM directive resets ARGS, so we specify again (the value is retained if
# previously set).
ARG CUDA

LABEL authors="Athanasios Baltzis, Jose Espinosa-Carrasco, Leila Mansouri" \
    title="nfcore/proteinfold_alphafold2_standard" \
    Version="dev" \
    description="Docker image containing all software requirements to run the RUN_ALPHAFOLD2 module using the nf-core/proteinfold pipeline"

# Use bash to support string substitution.
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Add env variables
ENV LD_LIBRARY_PATH="/usr/local/cuda-${CUDA}/lib64:$LD_LIBRARY_PATH"

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC
RUN apt-get update --quiet \
    && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y --quiet \
    build-essential \
    nvidia-cuda-dev \
    cuda-command-line-tools-$(cut -f1,2 -d- <<< ${CUDA//./-}) \
    git \
    wget \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get autoremove -y \
    && apt-get clean

# Install Miniforge package manager
RUN wget -q -P /tmp \
    "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh" \
    && bash /tmp/Miniforge3-$(uname)-$(uname -m).sh -b -p /opt/conda \
    && rm /tmp/Miniforge3-$(uname)-$(uname -m).sh

# Install ESMFold dependencies.
ENV PATH="/opt/conda/bin:$PATH"
ENV LD_LIBRARY_PATH="/opt/conda/lib:$LD_LIBRARY_PATH"
RUN conda install --quiet --yes conda pip python=3.9 \
    && conda install --quiet --yes --channel nvidia cuda=${CUDA} \
    && conda install --quiet --yes --channel conda-forge openmm=8.0.0 pdbfixer \
    && conda clean --all --force-pkgs-dirs --yes

# Install pip packages.
RUN pip install --no-cache-dir git+https://github.com/facebookresearch/esm.git
RUN pip install --no-cache-dir "fair-esm[esmfold]"
RUN pip install --no-cache-dir \
    biopython>=1.79 \
    deepspeed==0.5.9 \
    dm-tree==0.1.6 \
    ml-collections==0.1.0 \
    numpy>=1.21.2 \
    pytorch_lightning>=1.5.10 \
    PyYAML==5.4.1 \
    requests==2.26.0 \
    scipy==1.7.1 \
    torch>=2.4.0 \
    torchvision>=0.14.1 \
    tqdm==4.62.2 \
    typing-extensions==4 \
    wandb
RUN pip uninstall -y nvidia_cublas_cu12
RUN pip install --no-cache-dir 'dllogger @ git+https://github.com/NVIDIA/dllogger.git'
RUN pip install --no-cache-dir 'openfold @ git+https://github.com/aqlaboratory/openfold.git@23cf2f6107bf5753cfb12ce05895d66f2135d9cd'
